rabbit1:
  #image: bijukunjummen/rabbitmq-server
  image: rabbitmq-server
  ports:
    - 15672:15672  # management port (guest:guest)
    #- 5673:5672   # amqp port
    #- 25672:25672 # cluster port
  hostname: rabbit1
  environment:
    - RABBITMQ_ERLANG_COOKIE="abcdefg"
    - CLUSTERED=true
  volumes:
    #- /srv/rabbitmq/rabbit1/lib:/var/lib/rabbitmq
    #- /srv/rabbitmq/rabbit1/log:/var/log/rabbitmq
    - /etc/timezone:/etc/timezone
    - /etc/localtime:/etc/localtime:ro
  restart: always
  #command: rabbitmq-plugins enable rabbitmq_consistent_hash_exchange 

rabbit2:
  #image: bijukunjummen/rabbitmq-server
  image: rabbitmq-server
  ports:
    - 15673:15672  # management port (guest:guest)
    #- 5674:5672   # amqp port
    #- 25673:25672 # cluster port
  hostname: rabbit2
  links:
    - rabbit1
  environment:
    - RABBITMQ_ERLANG_COOKIE="abcdefg"
    - CLUSTERED=true
    - CLUSTER_WITH=rabbit1
    - RAM_NODE=true
  volumes:
    #- /srv/rabbitmq/rabbit2/lib:/var/lib/rabbitmq
    #- /srv/rabbitmq/rabbit2/log:/var/log/rabbitmq
    - /etc/timezone:/etc/timezone
    - /etc/localtime:/etc/localtime:ro
  restart: always
  #command: rabbitmq-plugins enable rabbitmq_consistent_hash_exchange

rabbit3:
  #image: bijukunjummen/rabbitmq-server
  image: rabbitmq-server
  ports:
    - 15674:15672  # management port (guest:guest)
    #- 5675:5672   # amqp port
    #- 25674:25672 # cluster port
  hostname: rabbit3
  links:
    - rabbit1
    - rabbit2
  environment:
    - RABBITMQ_ERLANG_COOKIE="abcdefg"
    - CLUSTERED=true
    - CLUSTER_WITH=rabbit1

  volumes:
    #- /srv/rabbitmq/rabbit3/lib:/var/lib/rabbitmq
    #- /srv/rabbitmq/rabbit3/log:/var/log/rabbitmq
    - /etc/timezone:/etc/timezone
    - /etc/localtime:/etc/localtime:ro
  restart: always
  #command: rabbitmq-plugins enable rabbitmq_consistent_hash_exchange

haproxy:
  image: haproxy
  ports:
    - 5672:5672
    - 20000:20000
  links:
    - rabbit1
    - rabbit2
    - rabbit3
  volumes:
    - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg  
  restart: always
