#!/bin/sh

docker exec -it rabbitclusterhaproxycompose_rabbit1_1 rabbitmq-plugins enable rabbitmq_mqtt rabbitmq_stomp rabbitmq_management  rabbitmq_management_agent rabbitmq_management_visualiser rabbitmq_federation rabbitmq_federation_management sockjs rabbitmq_consistent_hash_exchange
docker exec -it rabbitclusterhaproxycompose_rabbit2_1 rabbitmq-plugins enable rabbitmq_mqtt rabbitmq_stomp rabbitmq_management  rabbitmq_management_agent rabbitmq_management_visualiser rabbitmq_federation rabbitmq_federation_management sockjs rabbitmq_consistent_hash_exchange
docker exec -it rabbitclusterhaproxycompose_rabbit3_1 rabbitmq-plugins enable rabbitmq_mqtt rabbitmq_stomp rabbitmq_management  rabbitmq_management_agent rabbitmq_management_visualiser rabbitmq_federation rabbitmq_federation_management sockjs rabbitmq_consistent_hash_exchange
